### ISSUE TITLE
invalid response

### ISSUE THREAD

**Issue by sunbowei1986** [skanehira/preview-uml.vim#2]
![image](https://user-images.githubusercontent.com/6293466/103854038-e8b54b80-5085-11eb-9cee-3c0c9ad2f628.png)
hi i got invalid response after :previewUML command what could it be the problem?thx

**Comment by felipejoribeiro** [comment]
I have the same problem. 
I'm using neovim installed in wsl Ubuntu 20.04 in windows. 
Is my platform supported?
Thank you.

**Comment by sunbowei1986** [comment]
> I have the same problem.
> I'm using neovim installed in wsl Ubuntu 20.04 in windows.
> Is my platform supported?
> Thank you.
After I change browser to qutebroser from Firefox it works now u try

**Comment by felipejoribeiro** [comment]
Awesome. It works in ASCII art? 
The browser change must be system wide or it's a plugin configuration?
I changed systemwide and it didn't work  :(

**Comment by sunbowei1986** [comment]
Then you try to specify the provider of your vim ,run: checkhealth to find it and :h provider to see in detail it must be that existence multiple kind confused ur system and after run time it lost

**Comment by felipejoribeiro** [comment]
Everything seams right in my :checkhealth. 
Just python2 isn't supported.
Here:

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#mkdp#check
========================================================================
  - INFO: Platform: linux
  - INFO: Nvim Version: NVIM v0.4.3
  - INFO: Node version: v14.15.1

  - INFO: Script: /home/felipejoribeiro/.config/nvim/autoload/plugged/markdown-preview.nvim/app/server.js
  - INFO: Script exists: 1
  - OK: Using node

health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: Zathura should work properly!
  - OK: Compiler should work!

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v14.15.1
  - INFO: Neovim node.js host: /home/felipejoribeiro/.nvm/versions/node/v14.15.1/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

**Comment by skanehira** [comment]
Did you run plantuml server?

plantuml/plantuml-server:jetty

**Comment by felipejoribeiro** [comment]
Thanks for the response.
i've changed from wsl for a completely different setup:

OS: Arch Linux x86_64
Kernel: 5.10.17-1-lts
Terminal: alacritty

Still not working here. Same error message.
How can i run the server? it's possible to do it without docker?

**Comment by skanehira** [comment]
> How can i run the server? it's possible to do it without docker?

Yes, you can change endpoint with option `g:preview_uml_url` run the server without docker.
Please refer plantuml server repository and set up server without docker.

https://github.com/plantuml/plantuml-server#how-to-run-the-server

**Comment by felipejoribeiro** [comment]
That is perfect. Thank you very much!

**Comment by skanehira** [comment]
@felipejoribeiro If you still have some problems, let me know :)
